# Generated by Django 5.2.7 on 2025-11-03 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('electricity', 'Electricity'), ('food', 'Food'), ('waste', 'Waste')], max_length=20)),
                ('value', models.FloatField(help_text='Input value, e.g., km, kWh, kg')),
                ('carbon_equivalent', models.FloatField(editable=False, help_text='Calculated CO2 equivalent in kg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-date'],
            },
        ),
    ]
